name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_blue:
  #e2e: ^0.2.1
  #flutter_driver:
  #  sdk: flutter

flutter:
  uses-material-design: true


dependency_overrides:
  flutter_blue:
    path: ../flutter_blue
  flutter_blue_platform_interface:
    path: ../flutter_blue_platform_interface