name: flutter_blue
description:
  Flutter plugin for connecting and communicating with Bluetooth Low Energy devices,
  on Android and iOS
version: 0.8.0
homepage: https://github.com/pauldemarco/flutter_blue

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.0
  protobuf: ^2.0.0
  rxdart: ^0.26.0
  collection: ^1.14.13
  meta: ^1.2.3
  flutter_blue_linux: ^0.8.0  
  flutter_blue_platform_interface: ^0.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  #integration_test: ^1.0.2+2
  #flutter_driver:
  #  sdk: flutter

dependency_overrides:
  flutter_blue_platform_interface:
    path: ../flutter_blue_platform_interface
  flutter_blue_linux:
    path: ../flutter_blue_linux

flutter:
  plugin:
    platforms:
      android:
        package: com.pauldemarco.flutter_blue
        pluginClass: FlutterBluePlugin
      ios:
        pluginClass: FlutterBluePlugin
      macos:
        pluginClass: FlutterBluePlugin
      linux:
        default_package: flutter_blue_linux