name: flutter_blue_windows
description: Windows Implementation of flutter_blue
version: 0.8.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FlutterBlueWindowsPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_platform_interface: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_blue_platform_interface:
    path: ../flutter_blue_platform_interface
  

