name: flutter_blue_linux
description: Linux Implementation of flutter_blue
version: 0.8.1
homepage: https://github.com/pauldemarco/flutter_blue
publish_to: none

flutter:
  plugin:
    platforms:
      linux:
        fileName: flutter_blue_linux.dart
        dartPluginClass: FlutterBlueLinux
        pluginClass: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.0
  rxdart: ^0.26.0
  collection: ^1.14.13
  meta: ^1.2.3
  flutter_blue_platform_interface: ^0.8.1
  bluez:
    git:
      url: https://github.com/allbrightio/bluez.dart.git
      ref: feature/add_characteritic_functions
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  #integration_test: ^1.0.2+2
  #flutter_driver:
  #  sdk: flutter

dependency_overrides:
  bluez:
    path: ../bluez.dart
  flutter_blue_platform_interface:
    path: ../flutter_blue_platform_interface
  

